/**
 * Autogenerated by Thrift Compiler (0.10.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <thrift/cxxfunctional.h>
#include "snappydata_struct_CatalogPartitionObject.h"

#include <algorithm>
#include <ostream>

#include <thrift/TToString.h>

namespace io { namespace snappydata { namespace thrift {


CatalogPartitionObject::~CatalogPartitionObject() noexcept {
}


void CatalogPartitionObject::__set_spec(const std::map<std::string, std::string> & val) {
  this->spec = val;
}

void CatalogPartitionObject::__set_storage(const CatalogStorage& val) {
  this->storage = val;
}

void CatalogPartitionObject::__set_parameters(const std::map<std::string, std::string> & val) {
  this->parameters = val;
}

uint32_t CatalogPartitionObject::read(::apache::thrift::protocol::TProtocol* iprot) {

  uint32_t xfer = 0;
  std::string fname;
  ::apache::thrift::protocol::TType ftype;
  int16_t fid;

  xfer += iprot->readStructBegin(fname);

  using ::apache::thrift::protocol::TProtocolException;

  bool isset_spec = false;
  bool isset_storage = false;
  bool isset_parameters = false;

  while (true)
  {
    xfer += iprot->readFieldBegin(fname, ftype, fid);
    if (ftype == ::apache::thrift::protocol::T_STOP) {
      break;
    }
    switch (fid)
    {
      case 1:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->spec.clear();
            uint32_t _size426;
            ::apache::thrift::protocol::TType _ktype427;
            ::apache::thrift::protocol::TType _vtype428;
            xfer += iprot->readMapBegin(_ktype427, _vtype428, _size426);
            uint32_t _i430;
            for (_i430 = 0; _i430 < _size426; ++_i430)
            {
              std::string _key431;
              xfer += iprot->readString(_key431);
              std::string& _val432 = this->spec[_key431];
              xfer += iprot->readString(_val432);
            }
            xfer += iprot->readMapEnd();
          }
          isset_spec = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 2:
        if (ftype == ::apache::thrift::protocol::T_STRUCT) {
          xfer += this->storage.read(iprot);
          isset_storage = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      case 3:
        if (ftype == ::apache::thrift::protocol::T_MAP) {
          {
            this->parameters.clear();
            uint32_t _size433;
            ::apache::thrift::protocol::TType _ktype434;
            ::apache::thrift::protocol::TType _vtype435;
            xfer += iprot->readMapBegin(_ktype434, _vtype435, _size433);
            uint32_t _i437;
            for (_i437 = 0; _i437 < _size433; ++_i437)
            {
              std::string _key438;
              xfer += iprot->readString(_key438);
              std::string& _val439 = this->parameters[_key438];
              xfer += iprot->readString(_val439);
            }
            xfer += iprot->readMapEnd();
          }
          isset_parameters = true;
        } else {
          xfer += iprot->skip(ftype);
        }
        break;
      default:
        xfer += iprot->skip(ftype);
        break;
    }
    xfer += iprot->readFieldEnd();
  }

  xfer += iprot->readStructEnd();

  if (!isset_spec)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_storage)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  if (!isset_parameters)
    throw TProtocolException(TProtocolException::INVALID_DATA);
  return xfer;
}

uint32_t CatalogPartitionObject::write(::apache::thrift::protocol::TProtocol* oprot) const {
  uint32_t xfer = 0;
  xfer += oprot->writeStructBegin("CatalogPartitionObject");

  xfer += oprot->writeFieldBegin("spec", ::apache::thrift::protocol::T_MAP, 1);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->spec.size()));
    std::map<std::string, std::string> ::const_iterator _iter440;
    for (_iter440 = this->spec.begin(); _iter440 != this->spec.end(); ++_iter440)
    {
      xfer += oprot->writeString(_iter440->first);
      xfer += oprot->writeString(_iter440->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("storage", ::apache::thrift::protocol::T_STRUCT, 2);
  xfer += this->storage.write(oprot);
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldBegin("parameters", ::apache::thrift::protocol::T_MAP, 3);
  {
    xfer += oprot->writeMapBegin(::apache::thrift::protocol::T_STRING, ::apache::thrift::protocol::T_STRING, static_cast<uint32_t>(this->parameters.size()));
    std::map<std::string, std::string> ::const_iterator _iter441;
    for (_iter441 = this->parameters.begin(); _iter441 != this->parameters.end(); ++_iter441)
    {
      xfer += oprot->writeString(_iter441->first);
      xfer += oprot->writeString(_iter441->second);
    }
    xfer += oprot->writeMapEnd();
  }
  xfer += oprot->writeFieldEnd();

  xfer += oprot->writeFieldStop();
  xfer += oprot->writeStructEnd();
  return xfer;
}

void swap(CatalogPartitionObject &a, CatalogPartitionObject &b) {
  using ::std::swap;
  swap(a.spec, b.spec);
  swap(a.storage, b.storage);
  swap(a.parameters, b.parameters);
}

CatalogPartitionObject::CatalogPartitionObject(const CatalogPartitionObject& other442) {
  spec = other442.spec;
  storage = other442.storage;
  parameters = other442.parameters;
}
CatalogPartitionObject::CatalogPartitionObject( CatalogPartitionObject&& other443) noexcept {
  spec = std::move(other443.spec);
  storage = std::move(other443.storage);
  parameters = std::move(other443.parameters);
}
CatalogPartitionObject& CatalogPartitionObject::operator=(const CatalogPartitionObject& other444) {
  spec = other444.spec;
  storage = other444.storage;
  parameters = other444.parameters;
  return *this;
}
CatalogPartitionObject& CatalogPartitionObject::operator=(CatalogPartitionObject&& other445) noexcept {
  spec = std::move(other445.spec);
  storage = std::move(other445.storage);
  parameters = std::move(other445.parameters);
  return *this;
}
void CatalogPartitionObject::printTo(std::ostream& out) const {
  using ::apache::thrift::to_string;
  out << "CatalogPartitionObject(";
  out << "spec=" << to_string(spec);
  out << ", " << "storage=" << to_string(storage);
  out << ", " << "parameters=" << to_string(parameters);
  out << ")";
}

}}} // namespace
